import { CardData } from './card-helpers';

// Définition d'un groupe de cards (section)
export interface CardGroup {
  groupKey: string;
  groupLabel: string;
  layout: 'grid-3' | 'grid-2' | 'list'; // Type de layout pour cette section
  cards: CardData[];
}

// Définition de la structure d'une page avec ses cards
export interface PageCardsDefinition {
  pageKey: string;
  pageLabel: string;
  cards: CardData[]; // Toutes les cards (pour compatibilité)
  groups?: CardGroup[]; // Cards organisées par sections (optionnel)
}

// Définitions des cards par page (dans l'ordre du menu site)
export const PAGE_CARDS: PageCardsDefinition[] = [
  {
    pageKey: 'home',
    pageLabel: 'Accueil',
    cards: [
      {
        cardKey: 'hearing-test',
        imageSrc: '/images/hearing-test.jpg',
        title: 'Test auditif gratuit',
        description: 'Un test complet et sans engagement pour comprendre votre audition.',
        imageAlt: 'Test auditif avec casque professionnel',
        href: '/test-auditif-gratuit',
        imagePosition: 'center 35%',
        fallbackEmoji: '👂',
      },
      {
        cardKey: 'human-support',
        imageSrc: '/images/human-support.jpg',
        title: 'Accompagnement humain',
        description: 'Pas de jargon technique, pas de pression commerciale.',
        imageAlt: 'Accompagnement personnalisé et humain',
        href: '/notre-accompagnement',
        imagePosition: 'center center',
        fallbackEmoji: '💬',
      },
      {
        cardKey: 'personalized-follow-up',
        imageSrc: '/images/personalized-follow-up.jpg',
        title: 'Suivi personnalisé',
        description: 'Réglages progressifs, adaptations, suivi régulier.',
        imageAlt: 'Suivi personnalisé de votre appareil auditif',
        href: '/notre-accompagnement',
        imagePosition: 'center center',
        fallbackEmoji: '🔧',
      },
      {
        cardKey: 'quality-solutions',
        imageSrc: '/images/quality-solutions.jpg',
        title: 'Solutions de qualité',
        description: 'Oticon et Bernafon, deux marques reconnues.',
        imageAlt: 'Appareils auditifs de qualité',
        href: '/solutions-auditives',
        imagePosition: 'center center',
        fallbackEmoji: '🏆',
      },
      {
        cardKey: 'independent-center',
        imageSrc: '/images/independent-center.jpg',
        title: 'Centre indépendant',
        description: 'Pas d\'objectifs de vente, pas de réseau à satisfaire.',
        imageAlt: 'Centre auditif indépendant',
        href: '/notre-accompagnement',
        imagePosition: 'center center',
        fallbackEmoji: '🎯',
      },
      {
        cardKey: 'price-transparency',
        imageSrc: '/images/price-transparency.jpg',
        title: 'Transparence des prix',
        description: 'Prix clairs, remboursements expliqués.',
        imageAlt: 'Transparence des prix et remboursements',
        href: '/remboursements',
        imagePosition: 'center center',
        fallbackEmoji: '💰',
      },
    ],
    groups: [
      {
        groupKey: 'main-features',
        groupLabel: 'Pourquoi choisir Audire ?',
        layout: 'grid-3',
        cards: [
          {
            cardKey: 'hearing-test',
            imageSrc: '/images/hearing-test.jpg',
            title: 'Test auditif gratuit',
            description: 'Un test complet et sans engagement pour comprendre votre audition.',
            imageAlt: 'Test auditif avec casque professionnel',
            href: '/test-auditif-gratuit',
            imagePosition: 'center 35%',
            fallbackEmoji: '👂',
          },
          {
            cardKey: 'human-support',
            imageSrc: '/images/human-support.jpg',
            title: 'Accompagnement humain',
            description: 'Pas de jargon technique, pas de pression commerciale.',
            imageAlt: 'Accompagnement personnalisé et humain',
            href: '/notre-accompagnement',
            imagePosition: 'center center',
            fallbackEmoji: '💬',
          },
          {
            cardKey: 'personalized-follow-up',
            imageSrc: '/images/personalized-follow-up.jpg',
            title: 'Suivi personnalisé',
            description: 'Réglages progressifs, adaptations, suivi régulier.',
            imageAlt: 'Suivi personnalisé de votre appareil auditif',
            href: '/notre-accompagnement',
            imagePosition: 'center center',
            fallbackEmoji: '🔧',
          },
          {
            cardKey: 'quality-solutions',
            imageSrc: '/images/quality-solutions.jpg',
            title: 'Solutions de qualité',
            description: 'Oticon et Bernafon, deux marques reconnues.',
            imageAlt: 'Appareils auditifs de qualité',
            href: '/solutions-auditives',
            imagePosition: 'center center',
            fallbackEmoji: '🏆',
          },
          {
            cardKey: 'independent-center',
            imageSrc: '/images/independent-center.jpg',
            title: 'Centre indépendant',
            description: 'Pas d\'objectifs de vente, pas de réseau à satisfaire.',
            imageAlt: 'Centre auditif indépendant',
            href: '/notre-accompagnement',
            imagePosition: 'center center',
            fallbackEmoji: '🎯',
          },
          {
            cardKey: 'price-transparency',
            imageSrc: '/images/price-transparency.jpg',
            title: 'Transparence des prix',
            description: 'Prix clairs, remboursements expliqués.',
            imageAlt: 'Transparence des prix et remboursements',
            href: '/remboursements',
            imagePosition: 'center center',
            fallbackEmoji: '💰',
          },
        ],
      },
    ],
  },
  {
    pageKey: 'notre-accompagnement',
    pageLabel: 'Notre accompagnement',
    cards: [
      {
        cardKey: 'approach-step-contact',
        imageSrc: '/images/approach-contact.jpg',
        title: 'Premier contact',
        description: 'Vous nous appelez ou vous venez nous voir. On discute de votre situation, sans engagement.',
        imageAlt: 'Premier contact avec Audire',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '👋',
      },
      {
        cardKey: 'approach-step-test',
        imageSrc: '/images/approach-test.jpg',
        title: 'Test auditif gratuit',
        description: 'Un test complet de 30 minutes pour comprendre votre audition.',
        imageAlt: 'Test auditif professionnel',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🎧',
      },
      {
        cardKey: 'approach-step-conseil',
        imageSrc: '/images/approach-conseil.jpg',
        title: 'Conseil personnalisé',
        description: 'On vous propose des solutions adaptées à votre situation et à votre budget.',
        imageAlt: 'Conseil personnalisé',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '💬',
      },
      {
        cardKey: 'approach-step-essai',
        imageSrc: '/images/approach-essai.jpg',
        title: 'Essai sans engagement',
        description: 'Vous testez les appareils dans votre quotidien.',
        imageAlt: 'Essai d\'appareil auditif',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🔍',
      },
      {
        cardKey: 'approach-step-reglages',
        imageSrc: '/images/approach-reglages.jpg',
        title: 'Réglages progressifs',
        description: 'On se voit régulièrement pour affiner les réglages.',
        imageAlt: 'Réglages de l\'appareil',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🔧',
      },
      {
        cardKey: 'approach-step-suivi',
        imageSrc: '/images/approach-suivi.jpg',
        title: 'Suivi dans la durée',
        description: 'Même après l\'achat, on reste là pour vous accompagner.',
        imageAlt: 'Suivi à long terme',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🤝',
      },
      {
        cardKey: 'approach-independance',
        imageSrc: '/images/approach-independance.jpg',
        title: 'Indépendance',
        description: 'Centre indépendant, sans objectifs de vente imposés.',
        imageAlt: 'Centre indépendant',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🎯',
      },
      {
        cardKey: 'approach-transparence',
        imageSrc: '/images/approach-transparence.jpg',
        title: 'Transparence',
        description: 'Prix clairs, remboursements expliqués, pas de frais cachés.',
        imageAlt: 'Transparence des prix',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '💎',
      },
      {
        cardKey: 'approach-disponibilite',
        imageSrc: '/images/approach-disponibilite.jpg',
        title: 'Disponibilité',
        description: 'Un problème ? Une question ? On est là.',
        imageAlt: 'Disponibilité et réactivité',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '⚡',
      },
      {
        cardKey: 'approach-proximite',
        imageSrc: '/images/approach-proximite.jpg',
        title: 'Proximité',
        description: 'On prend le temps de vous écouter et de vous accompagner vraiment.',
        imageAlt: 'Proximité et écoute',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '💙',
      },
    ],
    groups: [
      {
        groupKey: 'steps',
        groupLabel: 'Comment ça se passe ? (Étape par étape)',
        layout: 'list',
        cards: [
          {
            cardKey: 'approach-step-contact',
            imageSrc: '/images/approach-contact.jpg',
            title: 'Premier contact',
            description: 'Vous nous appelez ou vous venez nous voir. On discute de votre situation, sans engagement.',
            imageAlt: 'Premier contact avec Audire',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '👋',
          },
          {
            cardKey: 'approach-step-test',
            imageSrc: '/images/approach-test.jpg',
            title: 'Test auditif gratuit',
            description: 'Un test complet de 30 minutes pour comprendre votre audition.',
            imageAlt: 'Test auditif professionnel',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🎧',
          },
          {
            cardKey: 'approach-step-conseil',
            imageSrc: '/images/approach-conseil.jpg',
            title: 'Conseil personnalisé',
            description: 'On vous propose des solutions adaptées à votre situation et à votre budget.',
            imageAlt: 'Conseil personnalisé',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '💬',
          },
          {
            cardKey: 'approach-step-essai',
            imageSrc: '/images/approach-essai.jpg',
            title: 'Essai sans engagement',
            description: 'Vous testez les appareils dans votre quotidien.',
            imageAlt: 'Essai d\'appareil auditif',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🔍',
          },
          {
            cardKey: 'approach-step-reglages',
            imageSrc: '/images/approach-reglages.jpg',
            title: 'Réglages progressifs',
            description: 'On se voit régulièrement pour affiner les réglages.',
            imageAlt: 'Réglages de l\'appareil',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🔧',
          },
          {
            cardKey: 'approach-step-suivi',
            imageSrc: '/images/approach-suivi.jpg',
            title: 'Suivi dans la durée',
            description: 'Même après l\'achat, on reste là pour vous accompagner.',
            imageAlt: 'Suivi à long terme',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🤝',
          },
        ],
      },
      {
        groupKey: 'differentiators',
        groupLabel: 'Ce qui nous différencie',
        layout: 'grid-2',
        cards: [
          {
            cardKey: 'approach-independance',
            imageSrc: '/images/approach-independance.jpg',
            title: 'Indépendance',
            description: 'Centre indépendant, sans objectifs de vente imposés.',
            imageAlt: 'Centre indépendant',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🎯',
          },
          {
            cardKey: 'approach-transparence',
            imageSrc: '/images/approach-transparence.jpg',
            title: 'Transparence',
            description: 'Prix clairs, remboursements expliqués, pas de frais cachés.',
            imageAlt: 'Transparence des prix',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '💎',
          },
          {
            cardKey: 'approach-disponibilite',
            imageSrc: '/images/approach-disponibilite.jpg',
            title: 'Disponibilité',
            description: 'Un problème ? Une question ? On est là.',
            imageAlt: 'Disponibilité et réactivité',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '⚡',
          },
          {
            cardKey: 'approach-proximite',
            imageSrc: '/images/approach-proximite.jpg',
            title: 'Proximité',
            description: 'On prend le temps de vous écouter et de vous accompagner vraiment.',
            imageAlt: 'Proximité et écoute',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '💙',
          },
        ],
      },
    ],
  },
  {
    pageKey: 'partenaires-pharmaciens',
    pageLabel: 'Partenaires pharmaciens',
    cards: [
      {
        cardKey: 'partner-expertise',
        imageSrc: '/images/partner-expertise.jpg',
        title: 'Expertise reconnue',
        description: 'Solutions Oticon et Bernafon, deux marques de référence mondiale en audiologie.',
        imageAlt: 'Expertise en audiologie',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🏆',
      },
      {
        cardKey: 'partner-accompagnement',
        imageSrc: '/images/partner-accompagnement.jpg',
        title: 'Accompagnement humain',
        description: 'Prise en charge personnalisée et suivi régulier de vos patients.',
        imageAlt: 'Accompagnement humain',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '💙',
      },
      {
        cardKey: 'partner-reactivite',
        imageSrc: '/images/partner-reactivite.jpg',
        title: 'Réactivité',
        description: 'Prise de rendez-vous rapide et disponibilité pour les urgences.',
        imageAlt: 'Réactivité',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '⚡',
      },
      {
        cardKey: 'partner-transparence',
        imageSrc: '/images/partner-transparence.jpg',
        title: 'Transparence',
        description: 'Prix clairs et explications détaillées des remboursements INAMI.',
        imageAlt: 'Transparence des prix',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '💎',
      },
      {
        cardKey: 'partner-independance',
        imageSrc: '/images/partner-independance.jpg',
        title: 'Indépendance',
        description: 'Centre indépendant sans objectifs de vente, focus sur le bien-être du patient.',
        imageAlt: 'Indépendance',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🎯',
      },
      {
        cardKey: 'partner-retour',
        imageSrc: '/images/partner-retour.jpg',
        title: 'Retour d\'information',
        description: 'Nous vous tenons informé du suivi de vos patients (avec leur accord).',
        imageAlt: 'Retour d\'information',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🤝',
      },
    ],
    groups: [
      {
        groupKey: 'why-recommend',
        groupLabel: 'Pourquoi nous recommander ?',
        layout: 'grid-3',
        cards: [
          {
            cardKey: 'partner-expertise',
            imageSrc: '/images/partner-expertise.jpg',
            title: 'Expertise reconnue',
            description: 'Solutions Oticon et Bernafon, deux marques de référence mondiale en audiologie.',
            imageAlt: 'Expertise en audiologie',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🏆',
          },
          {
            cardKey: 'partner-accompagnement',
            imageSrc: '/images/partner-accompagnement.jpg',
            title: 'Accompagnement humain',
            description: 'Prise en charge personnalisée et suivi régulier de vos patients.',
            imageAlt: 'Accompagnement humain',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '💙',
          },
          {
            cardKey: 'partner-reactivite',
            imageSrc: '/images/partner-reactivite.jpg',
            title: 'Réactivité',
            description: 'Prise de rendez-vous rapide et disponibilité pour les urgences.',
            imageAlt: 'Réactivité',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '⚡',
          },
          {
            cardKey: 'partner-transparence',
            imageSrc: '/images/partner-transparence.jpg',
            title: 'Transparence',
            description: 'Prix clairs et explications détaillées des remboursements INAMI.',
            imageAlt: 'Transparence des prix',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '💎',
          },
          {
            cardKey: 'partner-independance',
            imageSrc: '/images/partner-independance.jpg',
            title: 'Indépendance',
            description: 'Centre indépendant sans objectifs de vente, focus sur le bien-être du patient.',
            imageAlt: 'Indépendance',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🎯',
          },
          {
            cardKey: 'partner-retour',
            imageSrc: '/images/partner-retour.jpg',
            title: 'Retour d\'information',
            description: 'Nous vous tenons informé du suivi de vos patients (avec leur accord).',
            imageAlt: 'Retour d\'information',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🤝',
          },
        ],
      },
    ],
  },
  {
    pageKey: 'solutions-auditives',
    pageLabel: 'Solutions auditives',
    cards: [
      {
        cardKey: 'solution-oticon',
        imageSrc: '/images/solution-oticon.jpg',
        title: 'Oticon',
        description: 'Technologie BrainHearing™, connexion Bluetooth, design discret, batterie rechargeable.',
        imageAlt: 'Marque Oticon',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🔵',
      },
      {
        cardKey: 'solution-bernafon',
        imageSrc: '/images/solution-bernafon.jpg',
        title: 'Bernafon',
        description: 'Excellent rapport qualité/prix, facilité d\'utilisation, confort toute la journée.',
        imageAlt: 'Marque Bernafon',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🟢',
      },
      {
        cardKey: 'solution-contour',
        imageSrc: '/images/solution-contour.jpg',
        title: 'Le contour d\'oreille',
        description: 'Modèle polyvalent et simple d\'utilisation, convient à presque tous les degrés de perte auditive.',
        imageAlt: 'Contour d\'oreille',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🎧',
      },
      {
        cardKey: 'solution-intra',
        imageSrc: '/images/solution-intra.jpg',
        title: 'L\'intra-auriculaire',
        description: 'Discrétion maximale, moulage personnalisé pour un confort optimal.',
        imageAlt: 'Intra-auriculaire',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '👁️',
      },
      {
        cardKey: 'solution-intent',
        imageSrc: '/images/solution-intent.jpg',
        title: 'Oticon Intent',
        description: 'Adaptation automatique à chaque situation avec capteurs de mouvement intégrés.',
        imageAlt: 'Oticon Intent',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '⭐',
      },
    ],
    groups: [
      {
        groupKey: 'brands',
        groupLabel: 'Oticon & Bernafon',
        layout: 'grid-2',
        cards: [
          {
            cardKey: 'solution-oticon',
            imageSrc: '/images/solution-oticon.jpg',
            title: 'Oticon',
            description: 'Technologie BrainHearing™, connexion Bluetooth, design discret, batterie rechargeable.',
            imageAlt: 'Marque Oticon',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🔵',
          },
          {
            cardKey: 'solution-bernafon',
            imageSrc: '/images/solution-bernafon.jpg',
            title: 'Bernafon',
            description: 'Excellent rapport qualité/prix, facilité d\'utilisation, confort toute la journée.',
            imageAlt: 'Marque Bernafon',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🟢',
          },
        ],
      },
      {
        groupKey: 'types',
        groupLabel: 'Types d\'appareils',
        layout: 'grid-3',
        cards: [
          {
            cardKey: 'solution-contour',
            imageSrc: '/images/solution-contour.jpg',
            title: 'Le contour d\'oreille',
            description: 'Modèle polyvalent et simple d\'utilisation, convient à presque tous les degrés de perte auditive.',
            imageAlt: 'Contour d\'oreille',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🎧',
          },
          {
            cardKey: 'solution-intra',
            imageSrc: '/images/solution-intra.jpg',
            title: 'L\'intra-auriculaire',
            description: 'Discrétion maximale, moulage personnalisé pour un confort optimal.',
            imageAlt: 'Intra-auriculaire',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '👁️',
          },
          {
            cardKey: 'solution-intent',
            imageSrc: '/images/solution-intent.jpg',
            title: 'Oticon Intent',
            description: 'Adaptation automatique à chaque situation avec capteurs de mouvement intégrés.',
            imageAlt: 'Oticon Intent',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '⭐',
          },
        ],
      },
    ],
  },
  {
    pageKey: 'test-auditif-gratuit',
    pageLabel: 'Test gratuit',
    cards: [
      {
        cardKey: 'test-signs',
        imageSrc: '/images/test-signs.jpg',
        title: 'Les signes qui doivent alerter',
        description: 'Vous faites souvent répéter, vous augmentez le volume de la TV, vous avez du mal à suivre les conversations dans le bruit.',
        imageAlt: 'Signes de perte auditive',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🔍',
      },
      {
        cardKey: 'test-benefits',
        imageSrc: '/images/test-benefits.jpg',
        title: 'Les bénéfices d\'un dépistage précoce',
        description: 'Meilleure qualité de vie, relations sociales préservées, moins de fatigue au quotidien.',
        imageAlt: 'Bénéfices du dépistage',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '✨',
      },
      {
        cardKey: 'test-step-discussion',
        imageSrc: '/images/test-step-discussion.jpg',
        title: 'Discussion initiale (5 min)',
        description: 'On échange sur votre quotidien, vos difficultés, vos habitudes de vie.',
        imageAlt: 'Discussion initiale',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '💬',
      },
      {
        cardKey: 'test-step-visual',
        imageSrc: '/images/test-step-visual.jpg',
        title: 'Examen visuel (5 min)',
        description: 'Vérification de vos conduits auditifs avec un otoscope (sans douleur).',
        imageAlt: 'Examen visuel',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '👀',
      },
      {
        cardKey: 'test-step-hearing',
        imageSrc: '/images/test-step-hearing.jpg',
        title: 'Tests auditifs (15 min)',
        description: 'Vous écoutez différents sons à travers un casque. Aucune préparation nécessaire.',
        imageAlt: 'Tests auditifs',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '🎧',
      },
      {
        cardKey: 'test-step-results',
        imageSrc: '/images/test-step-results.jpg',
        title: 'Résultats et explications (5 min)',
        description: 'On vous explique vos résultats avec des mots simples et on répond à vos questions.',
        imageAlt: 'Résultats et explications',
        href: '#',
        imagePosition: 'center center',
        fallbackEmoji: '📊',
      },
    ],
    groups: [
      {
        groupKey: 'why-test',
        groupLabel: 'Pourquoi faire un test auditif ?',
        layout: 'grid-2',
        cards: [
          {
            cardKey: 'test-signs',
            imageSrc: '/images/test-signs.jpg',
            title: 'Les signes qui doivent alerter',
            description: 'Vous faites souvent répéter, vous augmentez le volume de la TV, vous avez du mal à suivre les conversations dans le bruit.',
            imageAlt: 'Signes de perte auditive',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🔍',
          },
          {
            cardKey: 'test-benefits',
            imageSrc: '/images/test-benefits.jpg',
            title: 'Les bénéfices d\'un dépistage précoce',
            description: 'Meilleure qualité de vie, relations sociales préservées, moins de fatigue au quotidien.',
            imageAlt: 'Bénéfices du dépistage',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '✨',
          },
        ],
      },
      {
        groupKey: 'test-steps',
        groupLabel: 'Comment se déroule le test ?',
        layout: 'list',
        cards: [
          {
            cardKey: 'test-step-discussion',
            imageSrc: '/images/test-step-discussion.jpg',
            title: 'Discussion initiale (5 min)',
            description: 'On échange sur votre quotidien, vos difficultés, vos habitudes de vie.',
            imageAlt: 'Discussion initiale',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '💬',
          },
          {
            cardKey: 'test-step-visual',
            imageSrc: '/images/test-step-visual.jpg',
            title: 'Examen visuel (5 min)',
            description: 'Vérification de vos conduits auditifs avec un otoscope (sans douleur).',
            imageAlt: 'Examen visuel',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '👀',
          },
          {
            cardKey: 'test-step-hearing',
            imageSrc: '/images/test-step-hearing.jpg',
            title: 'Tests auditifs (15 min)',
            description: 'Vous écoutez différents sons à travers un casque. Aucune préparation nécessaire.',
            imageAlt: 'Tests auditifs',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '🎧',
          },
          {
            cardKey: 'test-step-results',
            imageSrc: '/images/test-step-results.jpg',
            title: 'Résultats et explications (5 min)',
            description: 'On vous explique vos résultats avec des mots simples et on répond à vos questions.',
            imageAlt: 'Résultats et explications',
            href: '#',
            imagePosition: 'center center',
            fallbackEmoji: '📊',
          },
        ],
      },
    ],
  },
];

// Helper pour récupérer les cards d'une page spécifique
export function getDefaultCardsForPage(pageKey: string): CardData[] {
  const pageDef = PAGE_CARDS.find(p => p.pageKey === pageKey);
  return pageDef?.cards || [];
}

// Helper pour récupérer toutes les pages avec leurs cards (dans l'ordre du menu)
export function getAllPages(): PageCardsDefinition[] {
  const pageOrder = ['home', 'solutions-auditives', 'notre-accompagnement', 'partenaires-pharmaciens', 'test-auditif-gratuit'];
  return pageOrder
    .map(key => PAGE_CARDS.find(p => p.pageKey === key))
    .filter((p): p is PageCardsDefinition => p !== undefined);
}
